services:
  postgres:
    image: postgres:16
    container_name: financial-system-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financial-system-db

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d financial-system-db"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: financial-system-api

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/financial-system-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
