services:
  postgres:
    image: postgres:16
    container_name: financial-system-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financial-system
    ports:
      - "5432:5432"